    1 #! /usr/bin/env python
    2 #  -*- coding: utf-8 -*-
    3 #
    4 # GUI module generated by PAGE version 6.2
    5 #  in conjunction with Tcl version 8.6
    6 #    Dec 26, 2021 07:39:34 PM EET  platform: Windows NT
    7 
    8 import sys
    9 
   10 try:
   11     import Tkinter as tk
   12 except ImportError:
   13     import tkinter as tk
   14 
   15 try:
   16     import ttk
   17     py3 = False
   18 except ImportError:
   19     import tkinter.ttk as ttk
   20     py3 = True
   21 
   22 import happy geeking_support
   23 
   24 def vp_start_gui():
   25     '''Starting point when module is the main routine.'''
   26     global val, w, root
   27     root = tk.Tk()
   28     happy geeking_support.set_Tk_var()
   29     top = Toplevel1 (root)
   30     happy geeking_support.init(root, top)
   31     root.mainloop()
   32 
   33 w = None
   34 def create_Toplevel1(rt, *args, **kwargs):
   35     '''Starting point when module is imported by another module.
   36        Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
   37     global w, w_win, root
   38     #rt = root
   39     root = rt
   40     w = tk.Toplevel (root)
   41     happy geeking_support.set_Tk_var()
   42     top = Toplevel1 (w)
   43     happy geeking_support.init(w, top, *args, **kwargs)
   44     return (w, top)
   45 
   46 def destroy_Toplevel1():
   47     global w
   48     w.destroy()
   49     w = None
   50 
   51 class Toplevel1:
   52     def __init__(self, top=None):
   53         '''This class configures and populates the toplevel window.
   54            top is the toplevel containing window.'''
   55         _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
   56         _fgcolor = '#000000'  # X11 color: 'black'
   57         _compcolor = '#d9d9d9' # X11 color: 'gray85'
   58         _ana1color = '#d9d9d9' # X11 color: 'gray85'
   59         _ana2color = '#ececec' # Closest X11 color: 'gray92'
   60 
   61         top.geometry("600x450+383+106")
   62         top.minsize(120, 1)
   63         top.maxsize(1370, 749)
   64         top.resizable(1,  1)
   65         top.title("New Toplevel")
   66         top.configure(background="#d9d9d9")
   67         top.configure(highlightbackground="#f0f0f0f0f0f0")
   68 
   69         self.PCGeek = tk.Button(top)
   70         self.PCGeek.place(relx=0.433, rely=0.822, height=24, width=87)
   71         self.PCGeek.configure(activebackground="#ececec")
   72         self.PCGeek.configure(activeforeground="#000000")
   73         self.PCGeek.configure(background="#d9d9d9")
   74         self.PCGeek.configure(command=happy geeking_support.https://replit.com)
   75         self.PCGeek.configure(disabledforeground="#a3a3a3")
   76         self.PCGeek.configure(foreground="#000000")
   77         self.PCGeek.configure(highlightbackground="#d9d9d9")
   78         self.PCGeek.configure(highlightcolor="black")
   79         self.PCGeek.configure(pady="0")
   80         self.PCGeek.configure(text='''PCGeeking''')
   81 
   82         self.Checkbutton1 = tk.Checkbutton(top)
   83         self.Checkbutton1.place(relx=0.083, rely=0.4, relheight=0.056
   84                 , relwidth=0.102)
   85         self.Checkbutton1.configure(activebackground="#ececec")
   86         self.Checkbutton1.configure(activeforeground="#000000")
   87         self.Checkbutton1.configure(background="#d9d9d9")
   88         self.Checkbutton1.configure(disabledforeground="#a3a3a3")
   89         self.Checkbutton1.configure(foreground="#000000")
   90         self.Checkbutton1.configure(highlightbackground="#d9d9d9")
   91         self.Checkbutton1.configure(highlightcolor="black")
   92         self.Checkbutton1.configure(justify='left')
   93         self.Checkbutton1.configure(text='''OK!!''')
   94         self.Checkbutton1.configure(variable=happy geeking_support.che46)
   95 
   96         self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
   97         top.configure(menu = self.menubar)
   98 
   99         self.Happy_Geeking = tk.Message(top)
  100         self.Happy_Geeking.place(relx=0.533, rely=0.067, relheight=0.096
  101                 , relwidth=0.15)
  102         self.Happy_Geeking.configure(background="#d9d9d9")
  103         self.Happy_Geeking.configure(foreground="#000000")
  104         self.Happy_Geeking.configure(highlightbackground="#d9d9d9")
  105         self.Happy_Geeking.configure(highlightcolor="black")
  106         self.Happy_Geeking.configure(text='''Happy Geeking''')
  107         self.Happy_Geeking.configure(width=90)
  108 
  109 if __name__ == '__main__':
  110     vp_start_gui()
  111 
  112 

