    1 #! /usr/bin/env python
    2 #  -*- coding: utf-8 -*-
    3 #
    4 # GUI module generated by PAGE version 6.2
    5 #  in conjunction with Tcl version 8.6
    6 #    Feb 28, 2022 07:39:03 PM EET  platform: Windows NT
    7 
    8 import sys
    9 
   10 try:
   11     import Tkinter as tk
   12 except ImportError:
   13     import tkinter as tk
   14 
   15 try:
   16     import ttk
   17     py3 = False
   18 except ImportError:
   19     import tkinter.ttk as ttk
   20     py3 = True
   21 
   22 import PwaBuilder_support
   23 
   24 def vp_start_gui():
   25     '''Starting point when module is the main routine.'''
   26     global val, w, root
   27     root = tk.Tk()
   28     top = Toplevel1 (root)
   29     PwaBuilder_support.init(root, top)
   30     root.mainloop()
   31 
   32 w = None
   33 def create_Toplevel1(rt, *args, **kwargs):
   34     '''Starting point when module is imported by another module.
   35        Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
   36     global w, w_win, root
   37     #rt = root
   38     root = rt
   39     w = tk.Toplevel (root)
   40     top = Toplevel1 (w)
   41     PwaBuilder_support.init(w, top, *args, **kwargs)
   42     return (w, top)
   43 
   44 def destroy_Toplevel1():
   45     global w
   46     w.destroy()
   47     w = None
   48 
   49 class Toplevel1:
   50     def __init__(self, top=None):
   51         '''This class configures and populates the toplevel window.
   52            top is the toplevel containing window.'''
   53         _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
   54         _fgcolor = '#000000'  # X11 color: 'black'
   55         _compcolor = '#d9d9d9' # X11 color: 'gray85'
   56         _ana1color = '#d9d9d9' # X11 color: 'gray85'
   57         _ana2color = '#ececec' # Closest X11 color: 'gray92'
   58 
   59         top.geometry("600x450+383+106")
   60         top.minsize(120, 1)
   61         top.maxsize(1370, 749)
   62         top.resizable(1,  1)
   63         top.title("New Toplevel")
   64         top.configure(background="#d9d9d9")
   65 
   66         self.Button1 = tk.Button(top)
   67         self.Button1.place(relx=0.25, rely=0.867, height=24, width=257)
   68         self.Button1.configure(activebackground="#ececec")
   69         self.Button1.configure(activeforeground="#000000")
   70         self.Button1.configure(background="#d9d9d9")
   71         self.Button1.configure(disabledforeground="#a3a3a3")
   72         self.Button1.configure(foreground="#000000")
   73         self.Button1.configure(highlightbackground="#d9d9d9")
   74         self.Button1.configure(highlightcolor="black")
   75         self.Button1.configure(pady="0")
   76         self.Button1.configure(text='''https://www.pwabuilder.com/''')
   77 
   78         self.Entry1 = tk.Entry(top)
   79         self.Entry1.place(relx=0.217, rely=0.222, height=190, relwidth=0.59)
   80         self.Entry1.configure(background="white")
   81         self.Entry1.configure(disabledforeground="#a3a3a3")
   82         self.Entry1.configure(font="TkFixedFont")
   83         self.Entry1.configure(foreground="#000000")
   84         self.Entry1.configure(insertbackground="black")
   85 
   86 if __name__ == '__main__':
   87     vp_start_gui()
   88 
   89 

